#!/bin/bash
# Quick Start Guide for Keycloak Development & Deployment

echo "================================"
echo "Keycloak Quick Start Guide"
echo "================================"
echo ""

# Function to print colored output
print_section() {
    echo ""
    echo ">>> $1"
    echo ""
}

print_section "1. LOCAL DEVELOPMENT SETUP"
echo "Using docker-compose for local development:"
echo ""
echo "  # Start services (PostgreSQL + Keycloak)"
echo "  docker-compose up -d"
echo ""
echo "  # Access Keycloak"
echo "  Admin console: http://localhost:8080/admin"
echo "  Username: admin"
echo "  Password: admin123"
echo ""
echo "  # View logs"
echo "  docker-compose logs -f keycloak"
echo ""
echo "  # Stop services"
echo "  docker-compose down"
echo ""

print_section "2. BUILDING DOCKER IMAGE"
echo "  docker build -t keycloak-railway:latest ."
echo ""

print_section "3. ENVIRONMENT VARIABLES"
echo "  # Copy the example environment file"
echo "  cp .env.example .env"
echo ""
echo "  # Update .env with your values"
echo "  # NEVER commit .env to git"
echo ""

print_section "4. DEPLOYMENT TO RAILWAY"
echo "Prerequisites:"
echo "  - Railway account (https://railway.app)"
echo "  - Git repository connected"
echo "  - PostgreSQL service provisioned on Railway"
echo ""
echo "Steps:"
echo "  1. Push code to your Git repository"
echo "  2. Connect Railway to your GitHub repo"
echo "  3. Add PostgreSQL service to your Railway project"
echo "  4. Configure environment variables in Railway dashboard"
echo "  5. Railway will auto-deploy on each push to main"
echo ""
echo "See RAILWAY_DEPLOYMENT.md for detailed instructions"
echo ""

print_section "5. DATABASE OPERATIONS"
echo "  # Initialize database (automatic on first run)"
echo "  # If manual migration needed:"
echo ""
echo "  docker-compose exec postgres psql -U keycloak -d keycloak"
echo ""

print_section "6. HEALTH CHECKS"
echo "  # Check if Keycloak is ready"
echo "  curl http://localhost:8080/health/ready"
echo ""
echo "  # Check if Keycloak is alive"
echo "  curl http://localhost:8080/health/live"
echo ""

print_section "7. LOGS & DEBUGGING"
echo "  # View all logs"
echo "  docker-compose logs"
echo ""
echo "  # View Keycloak logs"
echo "  docker-compose logs keycloak"
echo ""
echo "  # Follow logs in real-time"
echo "  docker-compose logs -f"
echo ""
echo "  # View specific container logs"
echo "  docker logs keycloak-dev -f"
echo ""

print_section "8. SECURITY CHECKLIST"
echo "  [ ] Read SECURITY.md"
echo "  [ ] Change default admin password"
echo "  [ ] Configure HTTPS/SSL"
echo "  [ ] Enable audit logging"
echo "  [ ] Set up database backups"
echo "  [ ] Configure email for notifications"
echo ""

print_section "9. COMMON ISSUES"
echo ""
echo "  Issue: Port 8080 already in use"
echo "  Solution: Change port in docker-compose.yml or:"
echo "           docker-compose down"
echo "           docker system prune"
echo ""
echo "  Issue: Database connection error"
echo "  Solution: Check KC_DB_URL and credentials in .env"
echo "           Ensure PostgreSQL container is running"
echo ""
echo "  Issue: Admin console not loading"
echo "  Solution: Wait 40+ seconds for startup"
echo "           Check health endpoint: http://localhost:8080/health/ready"
echo ""

print_section "10. USEFUL RESOURCES"
echo "  - Keycloak Docs: https://www.keycloak.org/documentation"
echo "  - Railway Docs: https://docs.railway.app"
echo "  - Docker Docs: https://docs.docker.com"
echo "  - PostgreSQL Docs: https://www.postgresql.org/docs"
echo ""

print_section "11. NEXT STEPS"
echo "  1. Read RAILWAY_DEPLOYMENT.md for production deployment"
echo "  2. Review SECURITY.md for security best practices"
echo "  3. Configure themes in themes/ directory"
echo "  4. Add custom providers in providers/ directory"
echo "  5. Set up CI/CD with GitHub Actions (.github/workflows/)"
echo ""

echo "================================"
echo "Ready to deploy! Good luck! 🚀"
echo "================================"
